#!/bin/bash

SESSION=${1}
TASK_DIR=${HOME}/work/tasks
QUEUE_DIR=${TASK_DIR}/queue

SCREEN_SESSIONS=$(screen -list | awk '/[[:digit:]]+\.[[:alnum:]]+/{split($1,session,"."); print session[2];}')

cd ${QUEUE_DIR}

for d in *
    do
        ind="  "
        if ( echo $SCREEN_SESSIONS | grep -q $d )
        then
          ind="* "
        fi
        if [ -d $d -a ! -L $d ]
        then
            desc=""
            if [ -e $d/info ] 
                then 
                    desc=$(cat $d/info)
                else
                    desc="-------"
            fi
            echo -e "$ind$d\t$desc"
        fi
    done

for s in ${SCREEN_SESSIONS}
do
  if [ ! -d ${QUEUE_DIR}/${s} ] 
  then
    desc="--notask--"
    /bin/echo -e "? $s\t$desc"
  fi
done
